<?php if ($this->_isEnabled): ?>
<script type="text/javascript">
/* Jirafe Analytics */
(function(){
    var d=document,g=d.createElement('script'),s=d.getElementsByTagName('script')[0];
        g.type='text/javascript';g.defer=g.async=true;g.src=d.location.protocol+'//<?php echo $this->_beaconApiUrl ?>';
        s.parentNode.insertBefore(g,s);
})();
var jirafe_site_id = "<?php echo $this->_siteId ?>";
function jirafe_deferred(jirafe_api){
    jirafe_api.pageview(jirafe_site_id, "<?php echo $this->_getPage(); ?>");
}
</script>
<?php endif; 