<script type="text/javascript">
/* Jirafe Analytics */
(function(){
    var d=document,g=d.createElement('script'),s=d.getElementsByTagName('script')[0];
        g.type='text/javascript';g.defer=g.async=true;g.src=d.location.protocol+'//<?php echo $this->_beaconApiUrl ?>';
        s.parentNode.insertBefore(g,s);
})();
var jirafe_site_id = "<?php echo $this->_siteId ?>";
var jirafe_org_id = "";
function jirafe_deferred(jirafe_api){
    jirafe_api.pageview(jirafe_org_id, jirafe_site_id, "<?php echo $this->_page; ?>");
    <?php if ($this->_orderNumber): ?>
    jirafe_api.order.success(jirafe_org_id, jirafe_site_id, {
        order: {
            num: "<?php echo $this->_orderNumber ?>"
        }
    });
    <?php endif ?>
}
</script>